name: FactionUI
main: FactionUI\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.0.5
author: BajanVlogs

commands:
 factionui:
  description: "This is for Faction servers using CustomUI"
